image: tiangolo/docker-with-compose

before_script:
  - docker login -u $USR_HUB -p $PSS_HUB $CI_REGISTRY
  - echo "$DOTENV" > .env
  - pip install docker-auto-labels

stages:
  - test
  - build
  - deploy

tests:
  stage: test
  script:
    - docker network create traefik-public
    - sh ./scripts/test.sh
    #- echo "=O"


build-prod:
  stage: build
  script:
    - TAG=prod FRONTEND_ENV=production sh ./scripts/build-push.sh
  only:
    - main
  tags:
    - build
    - test


deploy-prod:
  stage: deploy
  script:
    - >
      DOMAIN=mobapp.klh.criptofesta.org
      TRAEFIK_TAG=mobapp.klh.criptofesta.org
      STACK_NAME=mobapp
      TAG=prod
      sh ./scripts/deploy.sh
  environment:
    name: production
    url: https://mobapp.klh.criptofesta.org
  only:
    - main
  tags:
    - swarm
    - prod
